# Adding latitude and longitude

## Read CSV file

In [1]:
csv_path = 'https://cocl.us/Geospatial_data'

In [2]:
import pandas as pd

In [8]:
latlong = pd.read_csv(csv_path)

In [23]:
latlong.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

## Scrape data from wikipedia into a dataframe (in a single code)

In [17]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M' 
url 

df = pd.read_html(url, header = 0) 

torronto = df[0]

torronto.dropna(subset =["Neighborhood"],axis = 0,inplace = True)

torronto.sort_values(['Postal Code'],ascending = True,axis= 0, inplace = True)

torronto.reset_index(inplace = True)

torronto.drop(['index'],axis = 1,inplace = True)


torronto.head()

  Postal Code      Borough                            Neighborhood
0         M1B  Scarborough                          Malvern, Rouge
1         M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2         M1E  Scarborough       Guildwood, Morningside, West Hill
3         M1G  Scarborough                                  Woburn
4         M1H  Scarborough                               Cedarbrae

## Add latitude and longitude columns to the torronto dataframe

In [20]:
torronto['Latitude'] = latlong['Latitude']
torronto['Longitude'] = latlong["Longitude"]

In [24]:
torronto.head()

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476